name: Sync repo files to Overleaf
on: workflow_dispatch
jobs:
  overleaf_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Set up the pip package
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            overleaf-sync
            opencv-python==4.1.2.30
      
      - name: Sync files to Overleaf
        run: |
          ols login
          ols -l -n ${{ github.event.repository.name }}
